export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS"

export const ADD_PRODUCT_TO_CART_SUCCESS="ADD_PRODUCT_TO_CART_SUCCESS"


export const GET_PRODUCT_FROM_CART_SUCCESS="GET_PRODUCT_FROM_CART_SUCCESS"

export const REMOVE_PRODUCT_FROM_CART_SUCCESS="REMOVE_PRODUCT_FROM_CART_SUCCESS"


